# Generated by Django 4.1 on 2022-11-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_problem_deadline_alter_problem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
