# Generated by Django 4.1 on 2022-11-06 07:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_problem_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
