# Generated by Django 4.1 on 2022-11-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_problem_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='whose_problem',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
